Feature/5351 shorted locale
wenzhixin/bootstrap-table pull request #5352
Opened 2020-09-29 20:01 UTC by kerog

**Bug fix?**
no

**New Feature?**
yes

**Resolve an issue?**
Fix #5351

**Example(s)?**
Sandbox not working with localization only shows English.

Additional add missing translations for Polish language pack.

2020-09-30 00:34 UTC, wenzhixin commented on src/locale/bootstrap-table-pl-PL.js
> + * Author: kerogos <kerog @ wp pl>
```js
 * Author: zergu <michal.zagdan @ gmail com>
 * Update: kerogos <kerog @ wp pl>
```

2020-09-30 01:41 UTC, djhvscf requested changes
Please change the header of the  file that @wenzhixin mentioned

2020-09-30 06:31 UTC, UtechtDustin commented
Also it would be greate if you add a sentence to the documentation which inform about this "feature" :-)

2020-09-30 11:01 UTC, kerog commented
> 
> 
> Also it would be greate if you add a sentence to the documentation which inform about this "feature" :-)

Ok, I found file Readme.md in src/locale folder, i add there information about all locale with short codes and missing translations.

Can I add simply reference to the this file in documentation?

2020-09-30 11:06 UTC, UtechtDustin commented
The Readme.md is the wrong file, you can find the Documentation here: https://github.com/wenzhixin/bootstrap-table/blob/develop/site/docs/api/localizations.md

Just add an Sentence like `Each Localization has a long and a short name, e.g. "af-ZA" and "af"`, we dont need a reference to this issue :-)

2020-09-30 11:14 UTC, kerog commented
During search of all locale I found in bootstrap-table locale dir translation for the non existing locale es-SP. I leave it, but you must consider delete it.

2020-09-30 11:28 UTC, kerog commented on src/locale/bootstrap-table-pl-PL.js
> + * Author: kerogos <kerog @ wp pl>
I changed it.

2020-09-30 15:17 UTC, djhvscf commented
How can we manage the localisations like es-CR? Since we have a lot of es-*

Any idea?

2020-09-30 16:06 UTC, kerog commented
> 
> 
> How can we manage the localisations like es-CR? Since we have a lot of es-*
> 
> Any idea @kerog ?

David, If you have locale differ from es-ES than you must use full locale eg 'es-CR', or if someone do translation for Deutch language for Austria, then he must use full locale 'de-AT', 'de' is reserved for 'de-DE'.

In src/locale/Readme.md I propose how to add new language based on https://www.alchemysoftware.com/livedocs/ezscript/Topics/Catalyst/Language.htm

2020-09-30 17:11 UTC, djhvscf commented
Ok, I was thinking that we could use the CR of es-CR as a identifier also.

The problem is what happen if we find more than one coincidence?

2020-09-30 17:23 UTC, kerog commented
> 
> 
> Ok, I was thinking that we could use the CR of es-CR as a identifier also.
> 
> The problem is what happen if we find more than one coincidence?

I think we must set short code only for most popular language, like en is short form for en-US, unless there will be problem with eg. Argentinian Spanish (es-AR) witch is short form of Arabian (Saudi Arabia).
We must use code from iso-639-1, eg CR is not for Costa Rica. There is language Cree

2020-10-01 09:18 UTC, kerog commented
Hi, what is wrong with travis-ci?
I'm waiting almost 24h for status from  travis. :(

2020-10-01 09:19 UTC, UtechtDustin commented
@wenzhixin Please check that.

2020-10-01 13:37 UTC, djhvscf commented
I just restarted the build. Let's wait

2020-10-01 13:37 UTC, djhvscf approved these changes

2020-10-01 13:38 UTC, merged