Fix print with rowspan / colspan
wenzhixin/bootstrap-table pull request #5397
Opened 2020-10-23 21:12 UTC by Moutard3

**Bug fix?**
yes

**New Feature?**
no

**Resolve an issue?**
Fix #5206

**Example(s)?**
Before: https://live.bootstrap-table.com/code/GCru/4115 (1.17) / https://live.bootstrap-table.com/code/Moutard3/5156 (1.18)
After: https://live.bootstrap-table.com/code/Moutard3/5155 (moutard3:fix/5206)

2020-10-24 05:47 UTC, djhvscf approved these changes

2020-10-24 05:47 UTC, djhvscf commented on src/extensions/print/bootstrap-table-print.js
> +    /*
Please uncomment these lines of code

2020-10-24 05:49 UTC, djhvscf requested changes
Please uncomment the lines 279 - 285

2020-10-25 10:27 UTC, Moutard3 commented
Sorry about that, though I did, but it wasn't added before commit

2020-10-27 02:40 UTC, wenzhixin approved these changes

2020-10-27 02:41 UTC, merged