Update translation
wenzhixin/bootstrap-table pull request #5450
Opened 2020-11-20 18:46 UTC by DarkThinking

**Bug fix?**
no

**New Feature?**
idk

**Resolve an issue?**
no

2020-11-21 04:03 UTC, djhvscf approved these changes

2020-11-21 04:04 UTC, djhvscf commented
Please review CI errors

2020-11-21 04:04 UTC, djhvscf requested changes
Please review CI errors

2020-11-27 23:13 UTC, UtechtDustin commented
@DarkThinking Could you fix the CI errors, so we can merge it :-) ?

2020-11-30 23:01 UTC, djhvscf commented
Hi! There is not any reply, in that case we are going to close this PR. Thanks!

2020-12-05 03:07 UTC, wenzhixin commented on src/locale/bootstrap-table-es-ES.js
> +    return 'Pantalla completa
`'Pantalla completa'`

2020-12-05 03:08 UTC, wenzhixin commented on src/locale/bootstrap-table-es-ES.js
> +    return 'Auto Recargar
`'Auto Recargar'`

2020-12-05 03:08 UTC, wenzhixin commented on src/locale/bootstrap-table-es-ES.js
> +    return 'IR
`'IR'`

2020-12-05 03:14 UTC, closed without merging