Allow exact match when searching term with accent
wenzhixin/bootstrap-table pull request #5582
Opened 2021-02-08 00:07 UTC by pieral85

With attribute `data-search-accent-neutralise` set to `true`, searching with
a term containing an accent must return a result in case of exact match.

i.e.
Initial condition: `table` tag has `data-search-accent-neutralise="true"`
 - Before this commit, searching `josé` does NOT match data containing `josé`.
 - With this commit, searching `josé` matches data containing `josé`.

**Bug fix?**
yes

**New Feature?**
no

**Resolve an issue?**
Fix #5581

**Example(s)?**
[Before](https://live.bootstrap-table.com/example/options/search-accent-neutralise.html) (enter `josé` in the search bar)
[After](https://live.bootstrap-table.com/code/pieral85/6514) (enter `josé` in the search bar)

2021-02-08 00:31 UTC, pieral85 commented
In my original PR message, the example in the link [After](https://live.bootstrap-table.com/code/pieral85/6514) is not working,
as I don't have any development branch on this repo to provide (`Libraries` > `GitHub src branch`).

Does someone have any idea how I can attach my [forked branch](https://github.com/pieral85/bootstrap-table/tree/fix/5581) in the BT online editor?

2021-02-08 08:13 UTC, UtechtDustin commented
@pieral85 Thank you for the PR, but you editet the dist files instead of the soure files.
That means we can't merge this PR, please modify the source file and push it again.

In the editor you can use your Branch using `<username>:<branch>` e.g. `pieral85:fix/5581`.

2021-02-08 08:14 UTC, UtechtDustin requested changes
Edit the source file(s) instead the dist file(s).

2021-02-10 22:38 UTC, pieral85 commented
@UtechtDustin Thank you for your reply and advice.

Commit has been changed as requested.

2021-02-11 08:48 UTC, UtechtDustin approved these changes

2021-02-11 08:48 UTC, merged

2021-02-11 08:48 UTC, UtechtDustin commented
Looks good, thank you ! :-)