Feature/add
wenzhixin/bootstrap-table pull request #6077
Opened 2022-03-12 14:48 UTC by wenzhixin

**🤔Type of Request**
- [ ] **Bug fix**
- [x] **New feature**
- [ ] **Improvement**
- [ ] **Documentation**
- [ ] **Other**

**🔗Resolves an issue?**
Fix #6058
Fix #6057

**📝Changelog**

* Added update sortable support of updateColumnTitle method.
* Added `column-switch-all` event of toggle all columns.

- [x] **Core**
- [ ] **Extensions**

**💡Example(s)?**
**updateColumnTitle**
Before: https://live.bootstrap-table.com/code/antonioaltamura/10565
After: https://live.bootstrap-table.com/code/wenzhixin/10788

**`column-switch-all`**
https://live.bootstrap-table.com/code/wenzhixin/10789

**☑️Self Check before Merge**

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

2022-03-13 11:38 UTC, UtechtDustin requested changes
I don't think it makes sense that you can update the sortable option via method `updateColumnTitle`.
As the method name already says update column TITLE.

Then we have a method which name says update title but also could update the sortable option.

2022-03-13 12:39 UTC, wenzhixin commented
Do you think add a new method like `updateColumnSortable`?

2022-03-13 17:24 UTC, UtechtDustin commented
I guess a method `updateColumn` or `updateColumnOptions` makes more sense. so we can implement mehr stuff.
But i wonder that we don't have a method like this.

2022-03-14 04:14 UTC, djhvscf requested changes

2022-03-14 04:14 UTC, djhvscf commented on src/bootstrap-table.js
> +          $(el).data(column)
we're instantiating a lot of jquery object with $(el). I think we could use something like const element = $(el);

2022-05-13 21:43 UTC, UtechtDustin commented
Any news here @wenzhixin  ?

2022-05-14 08:44 UTC, wenzhixin commented
> But i wonder that we don't have a method like this.

I think it's okay to set it up directly with the `refreshOptions` method.

So let's close this PR?

2022-05-14 13:05 UTC, djhvscf commented
We can either change the method name or implement a new method where we can change all the column config

2022-05-14 17:56 UTC, UtechtDustin commented
I think we should add a new method which allowes to change all column options as @djhvscf said, but i guess this has no high priority yet.
So the "workaround" using the `refreshOptions`  is ok for now.

2022-05-14 17:56 UTC, closed without merging