Fixed XSS vulnerability bug by onCellHtmlData
wenzhixin/bootstrap-table pull request #6145
Opened 2022-05-10 03:45 UTC by wenzhixin

**🤔Type of Request**
- [x] **Bug fix**
- [ ] **New feature**
- [ ] **Improvement**
- [ ] **Documentation**
- [ ] **Other**

**🔗Resolves an issue?**
Fix #6144 
Fix #4005

**📝Changelog**

- [ ] **Core**
- [x] **Extensions**

Fixed XSS vulnerability bug by onCellHtmlData.

**💡Example(s)?**
* #6144
Before: https://live.bootstrap-table.com/code/uberbrady/11033
After: https://live.bootstrap-table.com/code/wenzhixin/11422

* #4005
https://live.bootstrap-table.com/code/wenzhixin/11423

**☑️Self Check before Merge**

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

2022-05-12 06:23 UTC, djhvscf commented
For the export plugin the example is not working, this is the error: Cannot read properties of undefined (reading 'fileName')

2022-05-12 06:25 UTC, djhvscf requested changes
For the export plugin the example is not working, this is the error: Cannot read properties of undefined (reading 'fileName')

The filter control example works as expected

2022-05-12 06:30 UTC, UtechtDustin commented
Don't work for me either, but i get the error message `Uncaught TypeError: o.exportOptions is undefined`

2022-05-14 10:18 UTC, wenzhixin commented
Updated the example: https://live.bootstrap-table.com/code/wenzhixin/11486

2022-05-14 13:02 UTC, djhvscf approved these changes

2022-05-14 13:02 UTC, merged