Bug fix in Searching formatted Columns using ColumnOptions Context
wenzhixin/bootstrap-table pull request #6360
Opened 2022-08-25 15:51 UTC by adragon202

Fixed bug in bootstrap-table-filter-control.js where calculateObjectValue would set the formatter context to the header instead of the ColumnOptions.

**🤔Type of Request**
- [x] **Bug fix**
- [ ] **New feature**
- [ ] **Improvement**
- [ ] **Documentation**
- [ ] **Other**

**🔗Resolves an issue?**

**📝Changelog**

- [ ] **Core**
- [x] **Extensions**

**💡Example(s)?**

**☑️Self Check before Merge**

⚠️ Please check all items below before review. ⚠️

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] Changelog is provided or not needed

2022-08-25 17:45 UTC, djhvscf commented
Please provide an [Online Example](https://live.bootstrap-table.com/) to show this PR working, thanks!

2022-08-25 17:45 UTC, djhvscf requested changes
This needs an example where we can reproduce the issue and an example where the issue is fixed.

2022-08-25 18:07 UTC, adragon202 commented
Created Example to demonstrate issue.

2022-09-12 05:26 UTC, djhvscf commented
The example doesn't work. Please review it and provide a new one.

2022-09-12 06:28 UTC, UtechtDustin commented
@djhvscf I guess this is the `before` example, i added his branch to the example and it seems working.
After: https://live.bootstrap-table.com/code/UtechtDustin/12803

2022-09-12 06:28 UTC, UtechtDustin approved these changes

2022-09-22 21:33 UTC, djhvscf approved these changes

2022-09-22 21:35 UTC, merged